base_url = "https://velnbur.xyz"

title = "Velnbur's Site"
description = "I'm Velnbur (Kyrylo Baibula) Software Developer, and this is my personal site for projects, blog, articles, CSV and many more."
theme = "anemone"

compile_sass = true
minify_html = true
build_search_index = true
generate_feeds = true
taxonomies = [
    {name = "articles", feed = true},
    {name = "blog", feed = true},
    {name = "csv", feed = true},
    {name = "projects", feed = true}
]

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true

[markdown]
highlight_code = true
render_emoji = true

[extra]
author = "Velnbur (Kyrylo Baibula)"
display_author = true
list_pages = true
header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/articles", name_en = "/articles/" },
  { url = "/blog", name_en = "/blog/" },
  { url = "/projects", name_en = "/projects/" },
  { url = "/csv", name_en = "/csv/" },
]
